--- Packaged-build metadata. `build_info.lua` is generated by dev/build.sh and is absent
--- in local development trees.
local ok, info = pcall(require, "build_info")
local release = ok and type(info) == "table" and info.release == true
local timestamp = (not release) and ok and type(info) == "table" and type(info.timestamp) == "string"
    and info.timestamp or nil

return {
    release = release,
    timestamp = timestamp,
}
