--- Packaged-build metadata. `build_info.lua` is generated by dev/build.sh and is absent
--- in local development trees.
local ok, info = pcall(require, "build_info")
local has = ok and type(info) == "table"
local release = has and info.release == true
local timestamp = (not release) and has and type(info.timestamp) == "string"
    and info.timestamp or nil

--- The commit the artifact was cut from, with "-dirty" appended when the tree had
--- uncommitted changes at build time. nil in a development tree, which is itself the
--- answer: nothing was packaged. `benchmark.txt` prints it so two reports can be told
--- apart, which is the only thing that makes a before/after pair mean anything.
local commit = has and type(info.commit) == "string" and info.commit or nil
local target = has and type(info.target) == "string" and info.target or nil

return {
    release = release,
    timestamp = timestamp,
    commit = commit,
    target = target,
}
