-- Consumable cards (Tarot / Planet) stored outside the deck.
-- Tarot metadata:
--   select = { exact = N } or { min = a, max = b } ("at least" style when min/max).
--   spawn = { kind = "tarot"|"planet", count = k } — adds up to k items, limited by free slots after use.
--   spawn_joker = true — needs a free Joker slot.
--   wheel_of_fortune = true — needs ≥1 owned Joker.
--   fool_duplicate = true — duplicates last used Tarot/Planet this run (not Fool).
-- `atlas` must exist in `Game.ASSET_ATLAS`. Major arcana `index` matches typical 0..21 sheet order.

CONSUMABLE_DEFS = {
    tarot_fool = {
        id = "tarot_fool",
        kind = "tarot",
        name = "The Fool",
        atlas = "Tarot",
        index = 0,
        fool_duplicate = true,
        select = { exact = 0 },
        tooltip = {
            "Creates the last Tarot or Planet card used during this run.",
            "The Fool excluded",
        },
    },
    tarot_magician = {
        id = "tarot_magician",
        kind = "tarot",
        name = "The Magician",
        atlas = "Tarot",
        index = 1,
        select = { min = 1, max = 2 },
        tooltip = "Enhances 2 selected cards to Lucky Cards",
    },
    tarot_high_priestess = {
        id = "tarot_high_priestess",
        kind = "tarot",
        name = "The High Priestess",
        atlas = "Tarot",
        index = 2,
        spawn = { kind = "planet", count = 2 },
        select = { exact = 0 },
        tooltip = {
            "Creates up to 2 random Planet cards.",
            "(Must have room)",
        },
    },
    tarot_empress = {
        id = "tarot_empress",
        kind = "tarot",
        name = "The Empress",
        atlas = "Tarot",
        index = 3,
        select = { min = 1, max = 2 },
        tooltip = "Enhances 2 selected cards to Mult Cards",
    },
    tarot_emperor = {
        id = "tarot_emperor",
        kind = "tarot",
        name = "The Emperor",
        atlas = "Tarot",
        index = 4,
        spawn = { kind = "tarot", count = 2 },
        select = { exact = 0 },
        tooltip = {
            "Creates up to 2 random Tarot cards.",
            "(Must have room)",
        },
    },
    tarot_hierophant = {
        id = "tarot_hierophant",
        kind = "tarot",
        name = "The Hierophant",
        atlas = "Tarot",
        index = 5,
        select = { min = 1, max = 2 },
        tooltip = "Enhances 2 selected cards to Bonus Cards",
    },
    tarot_lovers = {
        id = "tarot_lovers",
        kind = "tarot",
        name = "The Lovers",
        atlas = "Tarot",
        index = 6,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Wild Card",
    },
    tarot_chariot = {
        id = "tarot_chariot",
        kind = "tarot",
        name = "The Chariot",
        atlas = "Tarot",
        index = 7,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Steel Card",
    },
    tarot_strength = {
        id = "tarot_strength",
        kind = "tarot",
        name = "Strength",
        atlas = "Tarot",
        index = 11,
        select = { min = 1, max = 2 },
        tooltip = "Increases rank of up to 2 selected cards by 1",
    },
    tarot_hermit = {
        id = "tarot_hermit",
        kind = "tarot",
        name = "The Hermit",
        atlas = "Tarot",
        index = 9,
        select = { exact = 0 },
        hermit_money = true,
        tooltip = {
            "Doubles money.",
            "(Max of $20)",
        },
    },
    tarot_wheel_of_fortune = {
        id = "tarot_wheel_of_fortune",
        kind = "tarot",
        name = "Wheel of Fortune",
        atlas = "Tarot",
        index = 10,
        wheel_of_fortune = true,
        select = { exact = 0 },
        tooltip = "1 in 4 chance to add Foil, Holographic,\n or Polychrome edition to a random Joker",
    },
    tarot_justice = {
        id = "tarot_justice",
        kind = "tarot",
        name = "Justice",
        atlas = "Tarot",
        index = 8,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Glass Card",
    },
    tarot_hanged_man = {
        id = "tarot_hanged_man",
        kind = "tarot",
        name = "The Hanged Man",
        atlas = "Tarot",
        index = 12,
        select = { min = 1, max = 2 },
        tooltip = "Destroys up to 2 selected cards",
    },
    tarot_death = {
        id = "tarot_death",
        kind = "tarot",
        name = "Death",
        atlas = "Tarot",
        index = 13,
        select = { exact = 2 },
        tooltip = {
            "Select 2 cards, convert the left card into the right card.",
            "(Drag to rearrange)",
        },
    },
    tarot_temperance = {
        id = "tarot_temperance",
        kind = "tarot",
        name = "Temperance",
        atlas = "Tarot",
        index = 14,
        select = { exact = 0 },
        temperance_money = true,
        tooltip = {
            "Gives the total sell value of all current Jokers.",
            "(Max of $50)",
        },
    },
    tarot_devil = {
        id = "tarot_devil",
        kind = "tarot",
        name = "The Devil",
        atlas = "Tarot",
        index = 15,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Gold Card",
    },
    tarot_tower = {
        id = "tarot_tower",
        kind = "tarot",
        name = "The Tower",
        atlas = "Tarot",
        index = 16,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Stone Card",
    },
    tarot_star = {
        id = "tarot_star",
        kind = "tarot",
        name = "The Star",
        atlas = "Tarot",
        index = 17,
        select = { min = 1, max = 3 },
        convert_suit = "Diamonds",
        tooltip = "Converts up to 3 selected cards to Diamonds",
    },
    tarot_moon = {
        id = "tarot_moon",
        kind = "tarot",
        name = "The Moon",
        atlas = "Tarot",
        index = 18,
        select = { min = 1, max = 3 },
        convert_suit = "Clubs",
        tooltip = "Converts up to 3 selected cards to Clubs",
    },
    tarot_sun = {
        id = "tarot_sun",
        kind = "tarot",
        name = "The Sun",
        atlas = "Tarot",
        index = 19,
        select = { min = 1, max = 3 },
        convert_suit = "Hearts",
        tooltip = "Converts up to 3 selected cards to Hearts",
    },
    tarot_world = {
        id = "tarot_world",
        kind = "tarot",
        name = "The World",
        atlas = "Tarot",
        index = 21,
        select = { min = 1, max = 3 },
        convert_suit = "Spades",
        tooltip = "Converts up to 3 selected cards to Spades",
    },
    tarot_judgement = {
        id = "tarot_judgement",
        kind = "tarot",
        name = "Judgement",
        atlas = "Tarot",
        index = 20,
        spawn_joker = true,
        select = { exact = 0 },
        tooltip = {
            "Creates a random Joker card.",
            "(Must have room)",
        },
    },
    planet_pluto = {
        id = "planet_pluto",
        kind = "planet",
        name = "Pluto",
        atlas = "Planet",
        hand = "High Card",
        index = 38,
    },
    planet_mercury = {
        id = "planet_mercury",
        kind = "planet",
        name = "Mercury",
        atlas = "Planet",
        hand = "Pair",
        index = 30,
    },
    planet_uranus = {
        id = "planet_uranus",
        kind = "planet",
        name = "Uranus",
        atlas = "Planet",
        hand = "Two Pair",
        index = 36
    },
    planet_venus = {
        id = "planet_venus",
        kind = "planet",
        name = "Venus",
        atlas = "Planet",
        hand = "Three of a Kind",
        index = 31,
    },
    planet_saturn = {
        id = "planet_saturn",
        kind = "planet",
        name = "Saturn",
        atlas = "Planet",
        hand = "Straight",
        index = 35,
    },
    planet_neptune = {
        id = "planet_neptune",
        kind = "planet",
        name = "Neptune",
        atlas = "Planet",
        hand = "Straight Flush",
        index = 37,
    },
    planet_mars = {
        id = "planet_mars",
        kind = "planet",
        name = "Mars",
        atlas = "Planet",
        hand = "Four of a Kind",
        index = 33,
    },
    planet_jupiter = {
        id = "planet_jupiter",
        kind = "planet",
        name = "Jupiter",
        atlas = "Planet",
        hand = "Flush",
        index = 34,
    },
    planet_earth = {
        id = "planet_earth",
        kind = "planet",
        name = "Earth",
        atlas = "Planet",
        hand = "Full House",
        index = 32,
    },
    planet_ceres = {
        id = "planet_ceres",
        kind = "planet",
        name = "Ceres",
        atlas = "Planet",
        hand = "Flush House",
        index = 28,
    },
    planet_x = {
        id = "planet_x",
        kind = "planet",
        name = "Planet X",
        atlas = "Planet",
        hand = "Five of a Kind",
        index = 29,
    },
    planet_eris = {
        id = "planet_eris",
        kind = "planet",
        name = "Eris",
        atlas = "Planet",
        hand = "Flush Five",
        index = 23
    },
    spectral_black_hole = {
        id = "spectral_black_hole",
        kind = "spectral",
        name = "Black Hole",
        atlas = "Spectral",
        tooltip = "Upgrade every poker hand by 1 level",
        index = 39,
    },
    spectral_familiar = {
        id = "spectral_familiar",
        kind = "spectral",
        name = "Familiar",
        atlas = "Spectral",
        tooltip = "Destroy 1 random card in your hand,\nadd 3 random Enhanced face cards to your hand",
        index = 40,
    },
    spectral_grim = {
        id = "spectral_grim",
        kind = "spectral",
        name = "Grim",
        atlas = "Spectral",
        tooltip = "Destroy 1 random card in your hand,\nadd 2 random Enhanced Aces to your hand",
        index = 41,
    },
    spectral_incantation = {
        id = "spectral_incantation",
        kind = "spectral",
        name = "Incantation",
        atlas = "Spectral",
        tooltip = "Destroy 1 random card in your hand,\nadd 4 random Enhanced numbered cards to your hand",
        index = 42,
    },
    spectral_talisman = {
        id = "spectral_talisman",
        kind = "spectral",
        name = "Talisman",
        atlas = "Spectral",
        select = { exact = 1 },
        tooltip = "Add a Gold Seal to 1 selected card",
        index = 43,
    },
    spectral_aura = {
        id = "spectral_aura",
        kind = "spectral",
        name = "Aura",
        atlas = "Spectral",
        select = { exact = 1 },
        tooltip = "Add Foil, Holographic, or Polychrome effect to 1 selected card",
        index = 44,
    },
    spectral_wraith = {
        id = "spectral_wraith",
        kind = "spectral",
        name = "Wraith",
        atlas = "Spectral",
        tooltip = "Creates a random Rare Joker,\nsets money to $0",
        index = 45,
    },
    spectral_sigil = {
        id = "spectral_sigil",
        kind = "spectral",
        name = "Sigil",
        atlas = "Spectral",
        tooltip = "Converts all cards in hand to a single random suit",
        index = 46,
    },
    spectral_ouija = {
        id = "spectral_ouija",
        kind = "spectral",
        name = "Ouija",
        atlas = "Spectral",
        tooltip = "Converts all cards in hand to a single random rank,\n-1 hand size",
        index = 47,
    },
    spectral_ectoplasm = {
        id = "spectral_ectoplasm",
        kind = "spectral",
        name = "Ectoplasm",
        atlas = "Spectral",
        tooltip = "Add Negative to a random Joker,\n-1 hand size",
        index = 48,
    },
    spectral_immolate = {
        id = "spectral_immolate",
        kind = "spectral",
        name = "Immolate",
        atlas = "Spectral",
        tooltip = "Destroys 5 random cards in hand,\ngain $20",
        index = 49,
    },
    spectral_ankh = {
        id = "spectral_ankh",
        kind = "spectral",
        name = "Ankh",
        atlas = "Spectral",
        tooltip = "Create a copy of a random Joker,\ndestroy all other Jokers",
        index = 50,
    },
    spectral_deja_vu = {
        id = "spectral_deja_vu",
        kind = "spectral",
        name = "Deja Vu",
        atlas = "Spectral",
        select = { exact = 1 },
        tooltip = "Add a Red Seal to 1 selected card",
        index = 51,
    },
    spectral_hex = {
        id = "spectral_hex",
        kind = "spectral",
        name = "Hex",
        atlas = "Spectral",
        tooltip = "Add Polychrome to a random Joker,\ndestroy all other Jokers",
        index = 52,
    },
    spectral_trance = {
        id = "spectral_trance",
        kind = "spectral",
        name = "Trance",
        atlas = "Spectral",
        select = { exact = 1 },
        tooltip = "Add a Blue Seal to 1 selected card",
        index = 53,
    },
    spectral_medium = {
        id = "spectral_medium",
        kind = "spectral",
        name = "Medium",
        atlas = "Spectral",
        select = { exact = 1 },
        tooltip = "Add a Purple Seal to 1 selected card",
        index = 54,
    },
    spectral_cryptid = {
        id = "spectral_cryptid",
        kind = "spectral",
        name = "Cryptid",
        atlas = "Spectral",
        select = { exact = 1 },
        tooltip = "Create 2 copies of 1 selected card",
        index = 55,
    },
    spectral_soul = {
        id = "spectral_soul",
        kind = "spectral",
        name = "The Soul",
        atlas = "Spectral",
        tooltip = "Creates a Legendary Joker,\n(Must have room)",
        index = 22,
    },

    
}
