--- Pixel-font construction, in two profiles.
---
--- On 3DS a `.ttf` path is rewritten to `.bcfnt` by the runtime
--- (`include/utilities/functions.hpp:42`), and a `.bcfnt` is a *bitmap* font: one pre-rasterised
--- glyph sheet with a fixed cell height. `TrueTypeRasterizer<Console::CTR>` turns the size passed
--- to `love.graphics.newFont` into a plain draw scale:
---
---     scale = floor(size * dpiScale + 0.5) / sheetInfo->cellHeight
---
--- (`platform/ctr/source/objects/truetyperasterizer_ext.cpp:32`; `GetDPIScale` is a hard 1.0 on
--- CTR, `include/modules/window/window.tcc:121`). So a size that does not equal the sheet's cell
--- height is a resample of pixel art, and it is a *smooth* one: the CTR branch of
--- `Font::CreateTexture` hardcodes `GPU_LINEAR` min/mag (`source/objects/font/font.cpp:221`) and
--- `Font::SetSamplerState` is an empty stub there (`font.cpp:721-725`), so `Font:setFilter` cannot
--- reach it. Nearest-neighbour is not available on hardware at all.
---
--- The shipped `m6x11plus.bcfnt` has a 33 px cell (baked at `mkbcfnt -s 22`), so under the SHARED
--- profile every size except LARGE is a bilinear reduction of that one sheet - SMALL, which is
--- roughly two thirds of the text in the game, at 1/3 scale.
---
--- The NATIVE profile asks for one sheet per size, each baked so its cell height *is* the
--- requested size, making every scale exactly 1.0. `dev/build.sh` generates those sheets; see
--- PIXEL_FONT_SHEETS in `dev/config.sh`, which must list the same cell heights as CELL_HEIGHTS
--- below (`tests/test_fonts.lua` fails if they drift).
---
--- None of this applies off-console: desktop LÖVE rasterises the `.ttf` at whatever size it is
--- given. The per-size files do not exist there, so `font_for` falls back to the shared face at
--- the *same* size - the profile still changes the metrics, so nest previews the layout change
--- even though it cannot preview the sharpness change.
local PerformanceLab = require("performance_lab")

local Fonts = {}

local SHARED_PATH = "resources/fonts/m6x11plus.ttf"
--- Per-cell-height faces generated by `dev/build.sh`. `%d` is the cell height, which is also the
--- size they must be loaded at.
local NATIVE_PATH_FORMAT = "resources/fonts/m6x11plus_h%d.ttf"

--- Cell heights `mkbcfnt` can actually produce from m6x11plus, measured off the generated files
--- rather than assumed: the tool's point-size argument is not the cell height, and two adjacent
--- point sizes often land on the same cell (`-s 21` and `-s 22` both give 33). Sizes outside this
--- set cannot be rendered 1:1 on hardware no matter what is requested.
Fonts.CELL_HEIGHTS = { 9, 13, 18, 22, 27, 33 }

--- Role -> requested pixel size.
---
--- NATIVE is what ships. SHARED is the historical ladder, kept so toggling the experiment is
--- still a true A/B against what was released before. NATIVE snaps each role to the nearest
--- available cell height *at or above* its current size. Rounding down would buy back a sheet or two, but the complaint this addresses is that
--- text reads small on a 240p screen, so trading legibility for sharpness would be answering the
--- wrong question (`tests/test_fonts.lua` enforces the direction).
---
--- Only three roles actually move. SMALL 11 -> 13 is the one that matters: it is roughly two
--- thirds of the text in the game. PRICE 15 -> 18 lands it on BUTTON's sheet for free. MICRO
--- 8 -> 9 is the smallest step the ladder offers, which is deliberate - MICRO carries the
--- boss-effect text into a ~76 px column on the top readout (`topUI.lua:248-250`) that wraps by
--- line count, so growing it overflows the block rather than just reading bigger.
Fonts.PROFILES = {
    shared = {
        MICRO = 8, TINY = 9, SMALL = 11, PRICE = 15,
        BUTTON = 18, MEDIUM = 22, BUTTON_PRICE = 26, LARGE = 33,
    },
    native = {
        MICRO = 9, TINY = 9, SMALL = 13, PRICE = 18,
        BUTTON = 18, MEDIUM = 22, BUTTON_PRICE = 27, LARGE = 33,
    },
}

--- NATIVE is the default. Every role is requested at a size some sheet was baked at, so the
--- draw scale is exactly 1.0 and text is rendered rather than resampled; SHARED remains for
--- the A/B, and is what the experiment toggles back to.
Fonts.DEFAULT_PROFILE = "native"

--- Role order is fixed so `apply` rebuilds deterministically and `next_smaller` walks a stable
--- set. It is not a size ordering: `next_smaller` sorts by height, because the roles collapse
--- onto shared faces differently in each profile.
local ROLES = {
    "MICRO", "TINY", "SMALL", "PRICE", "BUTTON", "MEDIUM", "BUTTON_PRICE", "LARGE",
}

--- Load one face. `nearest` filtering is set for desktop's benefit; it is inert on 3DS (see the
--- header) but costs nothing and keeps nest honest about the pixel grid.
local function load_font(path, size)
    local ok, font = pcall(love.graphics.newFont, path, size)
    if not ok or not font then return nil end
    if font.setFilter then
        pcall(font.setFilter, font, "nearest", "nearest")
    end
    return font
end

--- Face for one role under `profile`. The native profile prefers its per-size sheet and falls back
--- to the shared face at the *same size* when that file is absent, which is every non-3DS build.
--- Falling back on size as well would make nest and hardware disagree on layout, which is the one
--- thing the fallback must not do.
---@return love.Font|nil font
---@return boolean native True when the per-size face loaded (i.e. scale is 1.0 on hardware).
function Fonts.font_for(profile, size)
    if profile == "native" then
        local font = load_font(string.format(NATIVE_PATH_FORMAT, size), size)
        if font then return font, true end
    end
    return load_font(SHARED_PATH, size), false
end

--- Build a fresh `FONTS.PIXEL` table for `profile`.
---
--- The `<ROLE>_HEIGHT` numbers are read by layout code that needs a size before it has a font
--- (`topUI.lua:266`, `:272`, `:331`), so they are part of the table and have to be rebuilt with it
--- rather than captured once at boot.
---@param profile string|nil "shared" (default) or "native"
---@return table pixel
function Fonts.build(profile)
    profile = Fonts.PROFILES[profile] and profile or Fonts.DEFAULT_PROFILE
    local sizes = Fonts.PROFILES[profile]
    local pixel = { PROFILE = profile, FACES = 0, NATIVE_FACES = 0 }
    -- One face per *distinct* size, not per role: several roles share a size under the native
    -- profile, and each `newFont` linearAllocs its own copy of the whole glyph sheet on 3DS
    -- (there is no rasterizer cache in `wrap_graphics.cpp:398-420`), so a duplicate face is
    -- ~513 KB of a 64 MB machine spent on bytes that already exist.
    local by_size = {}
    for _, role in ipairs(ROLES) do
        local size = sizes[role]
        local font = by_size[size]
        if not font then
            local is_native
            font, is_native = Fonts.font_for(profile, size)
            by_size[size] = font
            pixel.FACES = pixel.FACES + 1
            if is_native then pixel.NATIVE_FACES = pixel.NATIVE_FACES + 1 end
        end
        pixel[role] = font
        pixel[role .. "_HEIGHT"] = size
    end
    return pixel
end

--- Swap `game.FONTS.PIXEL` to `profile` in place.
---
--- In place because UI code captures the table (`local P = game.FONTS.PIXEL`) even though it reads
--- the faces per call; replacing the table would strand those captures on the old faces.
---@param game table
---@param profile string|nil
---@return boolean changed
function Fonts.apply(game, profile)
    if not game or not game.FONTS or not game.FONTS.PIXEL then return false end
    profile = Fonts.PROFILES[profile] and profile or Fonts.DEFAULT_PROFILE
    local pixel = game.FONTS.PIXEL
    if pixel.PROFILE == profile then return false end

    local built = Fonts.build(profile)
    for key in pairs(pixel) do
        if built[key] == nil then pixel[key] = nil end
    end
    for key, value in pairs(built) do
        pixel[key] = value
    end

    -- The graphics module holds a reference to whatever font was last set, which would keep one
    -- retired face (and its sheet) alive indefinitely. Point it at a live face before collecting.
    if love and love.graphics and love.graphics.setFont and pixel.SMALL then
        love.graphics.setFont(pixel.SMALL)
    end
    -- Shop button labels are the only place a Font object is cached rather than looked up per
    -- draw (`shop_ui.lua:437-446`); the cache holds retired faces until it is dropped.
    game._shop_ui_cache = nil
    game._shop_layout_dirty = true
    collectgarbage("collect")
    return true
end

--- Largest role strictly smaller than `font`, or nil once there is nothing left to give up.
---
--- By height rather than by position in a list: roles collapse onto shared faces (PRICE and
--- BUTTON are one 18 px face under the native ladder, MICRO and TINY one 9 px face), so a
--- positional walk can hand back the same object it was given and spin whatever loop is calling
--- it. Strictly-smaller is the property callers actually depend on.
---@param game table
---@param font love.Font
---@return love.Font|nil
function Fonts.next_smaller(game, font)
    local pixel = game and game.FONTS and game.FONTS.PIXEL
    if not pixel or not font then return nil end

    local current
    for _, role in ipairs(ROLES) do
        if pixel[role] == font then
            local h = pixel[role .. "_HEIGHT"]
            if not current or h > current then current = h end
        end
    end
    if not current then return nil end

    local best, best_h
    for _, role in ipairs(ROLES) do
        local h = pixel[role .. "_HEIGHT"]
        if h and h < current and (not best_h or h > best_h) then
            best, best_h = pixel[role], h
        end
    end
    return best
end

--- Largest face at or below `font` that draws `text` within `max_w`, or the smallest there is.
---
--- A backstop, not a layout strategy: boxes should be sized for their contents. It exists because
--- a few labels are variable-length (boss blind names, a drained chips x mult product) and the box
--- around them is fixed, so the alternative is drawing past the edge - which is what the 3DS does
--- silently, since `printf` neither clips nor scrolls.
---
--- Note the ladder has no rung between 9 and 13: `mkbcfnt` cannot produce an 11 px cell from this
--- face, so a step down from SMALL is a big one. Prefer widening the box.
---@param game table
---@param font love.Font
---@param text string
---@param max_w number
---@return love.Font
function Fonts.fit(game, font, text, max_w)
    if not font or not font.getWidth or type(max_w) ~= "number" then return font end
    text = tostring(text or "")
    local candidate = font
    -- Bounded by the ladder: `next_smaller` is strictly smaller and returns nil at the floor.
    while candidate:getWidth(text) > max_w do
        local smaller = Fonts.next_smaller(game, candidate)
        if not smaller then break end
        candidate = smaller
    end
    return candidate
end

--- One line for the Performance Lab panel: which ladder is live, and how many of its faces
--- actually came from a per-size sheet.
---
--- The count is recorded when the face loads, not probed on the filesystem afterwards: on 3DS the
--- `.ttf` path is rewritten inside `newFont`, so the file the game names never exists on disk and
--- probing it would report zero while the fonts render perfectly. `native 0/5` under the native
--- profile means the sheets are missing from the build - which is normal off-console, and a build
--- failure on one. Without this the toggle looks identical either way on hardware.
---@return string line
function Fonts.status_line(game)
    local pixel = game and game.FONTS and game.FONTS.PIXEL
    local profile = (pixel and pixel.PROFILE) or Fonts.DEFAULT_PROFILE
    local faces = (pixel and pixel.FACES) or 0
    local native = (pixel and pixel.NATIVE_FACES) or 0
    return string.format("FONT %s  native %d/%d faces", profile, native, faces)
end

-- Native is the default now, so the toggle runs the other way: switching it OFF returns to the
-- historical shared ladder, which keeps the A/B available against what was released before.
PerformanceLab.register("crisp_fonts", {
    available = true,
    label = "Crisp fonts",
    default = true,
    on_change = function(enabled)
        if not G then return end
        Fonts.apply(G, enabled and "native" or "shared")
    end,
})

return Fonts
