[metadata]
title = "Balatro" # title of the game
author = "rosematcha" # author(s) of the game
description = "Balatro" # description of the game
version = "1.3.2" # current version, obeying semver
icons = { ctr = "game/resources/textures/1x/icon.png"} # custom icon paths

[build]
targets = ["ctr"]
source = "game"
packaged = true