--Voucher Catalog
-- Tier 2 entries use `depends_on` = Tier 1 id. Optional `price` (shop); default 10 in game if omitted.

VOUCHER_DEFS = {
    v_overstock = {
        id = "v_overstock",
        name = "Overstock",
        description = "+1 card slot available in shop (to 3 slots)",
        pos = 0,
        tier = 1,
    },
    v_overstock_plus = {
        id = "v_overstock_plus",
        name = "Overstock Plus",
        description = "+1 card slot available in shop (to 4 slots)",
        pos = 9,
        tier = 2,
        depends_on = "v_overstock",
    },
    v_clearance_sale = {
        id = "v_clearance_sale",
        name = "Clearance Sale",
        description = "All cards and packs in shop are 25% off",
        pos = 3,
        tier = 1,
    },
    v_liquidation = {
        id = "v_liquidation",
        name = "Liquidation",
        description = "All cards and packs in shop are 50% off",
        pos = 12,
        tier = 2,
        depends_on = "v_clearance_sale",
    },
    v_hone = {
        id = "v_hone",
        name = "Hone",
        description = "Foil, Holographic, and Polychrome\ncards appear 2X more often",
        pos = 4,
        tier = 1,
    },
    v_glow_up = {
        id = "v_glow_up",
        name = "Glow Up",
        description = "Foil, Holographic, and Polychrome\ncards appear 4X more often",
        pos = 13,
        tier = 2,
        depends_on = "v_hone",
    },
    v_reroll = {
        id = "v_reroll",
        name = "Reroll Surplus",
        description = "Rerolls cost $2 less",
        pos = 17,
        tier = 1,
    },
    v_reroll_glut = {
        id = "v_reroll_glut",
        name = "Reroll Glut",
        description = "Rerolls cost an additional $2 less",
        pos = 26,
        tier = 2,
        depends_on = "v_reroll",
    },
    v_crystal_ball = {
        id = "v_crystal_ball",
        name = "Crystal Ball",
        description = "+1 consumable slot",
        pos = 19,
        tier = 1,
    },
    v_omen_globe = {
        id = "v_omen_globe",
        name = "Omen Globe",
        description = "Spectral cards may appear in any\nof the Arcana Packs",
        pos = 28,
        tier = 2,
        depends_on = "v_crystal_ball",
    },
    v_telescope = {
        id = "v_telescope",
        name = "Telescope",
        description = "Celestial Packs always contain the Planet card\nfor your most played poker hand",
        pos = 20,
        tier = 1,
    },
    v_observatory = {
        id = "v_observatory",
        name = "Observatory",
        description = "Planet cards in your consumable area give\nX1.5 Mult for their specified poker hand",
        pos = 29,
        tier = 2,
        depends_on = "v_telescope",
    },
    v_wasteful = {
        id = "v_wasteful",
        name = "Wasteful",
        description = "Permanently gain +1 discard each round",
        pos = 6,
        tier = 1,
    },
    v_recyclomancy = {
        id = "v_recyclomancy",
        name = "Recyclomancy",
        description = "Permanently gain an additional +1 discard each round",
        pos = 15,
        tier = 2,
        unlock = "Discard a total of 2500 cards",
        depends_on = "v_wasteful",
    },
    v_tarot_merchant = {
        id = "v_tarot_merchant",
        name = "Tarot Merchant",
        description = "Tarot cards appear 2X more frequently in the shop",
        pos = 1,
        tier = 1,
    },
    v_tarot_tycoon = {
        id = "v_tarot_tycoon",
        name = "Tarot Tycoon",
        description = "Tarot cards appear 4X more frequently in the shop",
        pos = 10,
        tier = 2,
        unlock = "Buy a total of 50 Tarot cards from the shop",
        depends_on = "v_tarot_merchant",
    },
    v_planet_merchant = {
        id = "v_planet_merchant",
        name = "Planet Merchant",
        description = "Planet cards appear 2X more frequently in the shop",
        pos = 2,
        tier = 1,
    },
    v_planet_tycoon = {
        id = "v_planet_tycoon",
        name = "Planet Tycoon",
        description = "Planet cards appear 4X more frequently in the shop",
        pos = 11,
        tier = 2,
        unlock = "Buy a total of 50 Planet cards from the shop",
        depends_on = "v_planet_merchant",
    },
    v_seed_money = {
        id = "v_seed_money",
        name = "Seed Money",
        description = "Raise the cap on interest earned in each round to $10",
        pos = 18,
        tier = 1,
    },
    v_money_tree = {
        id = "v_money_tree",
        name = "Money Tree",
        description = "Raise the cap on interest earned in each round to $20",
        pos = 27,
        tier = 2,
        unlock = "Max out the interest per round earnings for ten consecutive rounds",
        depends_on = "v_seed_money",
    },
    v_blank = {
        id = "v_blank",
        name = "Blank",
        description = "Does nothing?",
        pos = 7,
        tier = 1,
    },
    v_antimatter = {
        id = "v_antimatter",
        name = "Antimatter",
        description = "+1 Joker slot",
        pos = 16,
        tier = 2,
        unlock = "Redeem Blank 10 total times",
        depends_on = "v_blank",
    },
    v_magic_trick = {
        id = "v_magic_trick",
        name = "Magic Trick",
        description = "Playing cards can be purchased from the shop",
        pos = 21,
        tier = 1,
    },
    v_illusion = {
        id = "v_illusion",
        name = "Illusion",
        description = "Playing cards in shop may have an Enhancement,\nEdition, and/or a Seal",
        pos = 30,
        tier = 2,
        unlock = "Buy a total of 20 Playing cards from the shop",
        depends_on = "v_magic_trick",
    },
    v_hieroglyph = {
        id = "v_hieroglyph",
        name = "Hieroglyph",
        description = "-1 Ante, -1 hand each round",
        pos = 22,
        tier = 1,
    },
    v_petroglyph = {
        id = "v_petroglyph",
        name = "Petroglyph",
        description = "-1 Ante again, -1 discard each round",
        pos = 31,
        tier = 2,
        unlock = "Reach Ante level 12",
        depends_on = "v_hieroglyph",
    },
    v_directors_cut = {
        id = "v_directors_cut",
        name = "Director's Cut",
        description = "Reroll Boss Blind 1 time per Ante, $10 per roll",
        pos = 23,
        tier = 1,
    },
    v_retcon = {
        id = "v_retcon",
        name = "Retcon",
        description = "Reroll Boss Blind unlimited times, $10 per roll",
        pos = 32,
        tier = 2,
        unlock = "Discover 25 Blinds",
        depends_on = "v_directors_cut",
    },
    v_paint_brush = {
        id = "v_paint_brush",
        name = "Paint Brush",
        description = "+1 hand size",
        pos = 24,
        tier = 1,
    },
    v_palette = {
        id = "v_palette",
        name = "Palette",
        description = "+1 hand size again",
        pos = 33,
        tier = 2,
        unlock = "Reduce your hand size down to 5 cards",
        depends_on = "v_paint_brush",
    },
    v_grabber = {
        id = "v_grabber",
        name = "Grabber",
        description = "Permanently gain +1 hand per round",
        pos = 5,
        tier = 1
    },
    v_nacho = {
        id = "v_nacho",
        name = "Nacho Tong",
        description = "Permanently gain an additional +1 hand per round",
        pos = 14,
        tier = 2,
        unlock = "Play a total of 2500 cards",
        depends_on = "v_grabber",
    },
}
